language: android

script:
    - cd GroendomChat
    - echo y | android update sdk --no-ui --all --filter "tool,extra-android-m2repository,extra-android-support,extra-google-google_play_services,extra-google-m2repository"
    - echo y | $ANDROID_HOME/tools/bin/sdkmanager "extras;m2repository;com;android;support;constraint;constraint-layout-solver;1.0.2"
    - gradle build connectedCheck --stacktrace
    
android:
    components:
        - tools
        - platform-tools
        - tools

        # The BuildTools version used by your project
        - build-tools-26.0.1

        # The SDK version used to compile your project
        - android-25
    
    licenses:
        - 'build-tools-26.0.1'
        - 'platform-tools'
        - 'android-sdk-preview-license-52d11cd2'
        - 'android-sdk-license-.+'
        - 'google-gdk-license-.+'
        - 'android-25'
        - 'google-m2repository'
        - 'extra-google-market_apk_expansion'
        - 'extra-google-market_licensing'
        - 'extra-google-play_billing'
        - 'extra-google-simulators'
        - 'extra-google-webdriver'
        - 'platform-tools'
        - 'source-14'
        - 'source-15'
        - 'source-16'
        - 'source-17'
        - 'source-18'
        - 'source-19'
        - 'source-20'
        - 'source-21'
        - 'source-22'
        - 'source-23'
        - 'source-24'
        - 'source-25'
        - '.+'

#env:
 #   global:
  #      - REPO="GroendomChat"