language: android

script:
    - cd GroendomChat
    - gradle build connectedCheck --stacktrace

android:
    components:
        - tools
        - platform-tools
        - tools

        # The BuildTools version used by your project
        - build-tools-26.0.1

        # The SDK version used to compile your project
        - android-25
    
    licenses:
        - 'build-tools-26.0.1'
        - 'platform-tools'
        - 'android-sdk-preview-license-52d11cd2'
        - 'android-sdk-license-.+'
        - 'google-gdk-license-.+'
        - 'android-25'
#env:
 #   global:
  #      - REPO="GroendomChat"