language: android

script:
    - cd GroendomChat
    - gradle build connectedCheck --stacktrace

android:
  components:
        - tools
        - platform-tools
        - tools

        # The BuildTools version used by your project
        - build-tools-26.0.0

        # The SDK version used to compile your project
        - android-25
    
    licenses:
        - 'android-sdk-license-25'
        - 'google-gdk-license-25'
#env:
 #   global:
  #      - REPO="GroendomChat"